### ISSUE TITLE
Document not defined

### ISSUE THREAD

**Issue by BEZEI2K** [Huddle/Resemble.js#32]
/Users/hulk/github/gameclash/tweetbot/node_modules/resemblejs/resemble.js:63
	var documentDomainRegex = new RegExp('^https?://' + document.domain);
	                                                    ^
ReferenceError: document is not defined
    at /Users/hulk/github/gameclash/tweetbot/node_modules/resemblejs/resemble.js:63:54
    at Object.<anonymous> (/Users/hulk/github/gameclash/tweetbot/node_modules/resemblejs/resemble.js:642:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/hulk/github/gameclash/tweetbot/app.js:62:16
    at Array.forEach (native)

**Comment by jamescryer** [comment]
I believe https://github.com/Huddle/Resemble.js/pull/35 fixed this script error
